# fly.toml app configuration file generated for translator-ai-bold-fire-3544 on 2025-09-26T18:10:00-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "translator-ai-white-resonance-7456"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
  [[services.ports]]
    port = 443

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
